--- #YAML:1.0
name:                Regexp-Wildcards
version:             0.01
abstract:            Converts wildcards expressions to Perl regular expressions.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Vincent Pit <perl@profvince.com>
