--- #YAML:1.0
name:                Regexp-Wildcards
version:             0.07
abstract:            Converts wildcard expressions to Perl regular expressions.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Exporter:                      0
    Test::More:                    0
    Text::Balanced:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Vincent Pit <perl@profvince.com>
